# Generated by Django 5.1.6 on 2025-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodo',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
